In [6]:
import numpy as np
import scipy.signal
a = 2 * np.ones((5,5))
c = np.stack((a, -a))
b = np.ones((2,2))
d = scipy.signal.convolve(a, b, mode = 'valid')
print(d.shape)
print(d)

(4, 4)
[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
